Repository ros2/rosdistro, pull requests merged in 2018-11, with the labels that each got.

#284 remove navigation2 release version for now
  bouncy/distribution.yaml
Labels: bug, in review

#282 add index v4
  index-v4.yaml
  test/test_indexes_equal.py
Labels: enhancement, in review

#286 Add crystal prerelease to rosdistro index.
  crystal/distribution.yaml
  index-v4.yaml
  index.yaml
Labels: in review

#356 Add unique_identifier_msgs to crystal distribution
  crystal/distribution.yaml
Labels: in review
